"""
city_models.py — Data models for citywide multi-route scheduling.

Phase 1: Whole-day fleet rebalancing across routes sharing a single depot.
Phase 2 hook: Transfer.reason supports "interlining" for trip-level cross-route.
"""

from __future__ import annotations
__version__ = "2026-04-08-p1"

from dataclasses import dataclass, field
from src.models import RouteConfig, BusState
from src.metrics import ScheduleMetrics
import pandas as pd


@dataclass
class RouteInput:
    """Everything needed to schedule one route — config + profiles."""
    config: RouteConfig
    headway_df: pd.DataFrame
    travel_time_df: pd.DataFrame


@dataclass
class RouteResult:
    """Output of scheduling a single route."""
    route_code: str
    config: RouteConfig
    headway_df: pd.DataFrame
    travel_time_df: pd.DataFrame
    buses: list[BusState]
    metrics: ScheduleMetrics
    pvr: int                    # Peak Vehicle Requirement (theoretical minimum)
    fleet_allocated: int        # actual buses assigned (after rebalancing)
    fleet_original: int         # fleet_size from config Excel
    surplus: int = 0            # positive = excess buses available to donate
    deficit: int = 0            # positive = route needs more buses
    physics_min_headway: int = 0    # ceil((cycle+RT)/fleet)+buffer — even-spacing minimum (peak)
    rec_peak_headway: int = 0       # recommended peak headway (k=1.0)
    rec_offpeak_headway: int = 0    # recommended off-peak headway (k=1.0)
    # Per-band recommended headway profile (list of dicts):
    #   [{"time_from":"08:00","time_to":"11:00","headway_min":27,"is_peak":True,"physics_min":27}, ...]
    # Populated by _run_single_route; usable directly as headway_df after user confirms.
    recommended_headway_profile: list = None
    # Planning-mode feasibility: "OK" | "INFEASIBLE" | "UNKNOWN"
    headway_feasibility_status: str = "UNKNOWN"
    # Per-band feasibility details for UI:
    #   [{"band":"08:00–11:00","cfg_hw":15,"physics_min":27,"status":"INFEASIBLE"}, ...]
    headway_feasibility_details: list = None
    # Audit: how was the current headway_df set?
    # "user"         → directly from input config or manual edit
    # "recommended"  → generated by k=1.0 auto-fill from dashboard
    # "scaled:k1.1"  → generated by k=X auto-fill from dashboard
    headway_source: str = "user"
    # Scaling parameters that produced recommended_headway_profile:
    headway_k: float = 1.0      # scaling factor applied to H_phys
    headway_alpha: float = 0.15  # off-peak spread: H_offpeak = H_peak × (1 + alpha)
    # Spike counts post-schedule — gaps > 2×H during non-peak hours.
    # Populated for all three scheduling modes using max(headway_df["headway_min"]) as H.
    # A single charging event typically contributes 1 to each direction (UP + DN = 2 total).
    spike_count_up: int = 0
    spike_count_dn: int = 0
    # Phase 2: depot simulation output
    depot_log: object = None    # DepotLog or None


@dataclass
class Transfer:
    """Record of a bus moved between routes during rebalancing."""
    bus_id: str
    from_route: str             # route_code donor (or "POOL" if unassigned)
    to_route: str               # route_code recipient
    reason: str = "surplus_rebalance"  # Phase 2: "interlining" | "soc_relief"


@dataclass
class CityConfig:
    """Aggregated city-level configuration."""
    routes: dict[str, RouteInput]       # route_code → RouteInput
    total_fleet: int = 0                # sum of all fleet_size (or user override)
    depot_name: str = "DEPOT"           # shared depot (Phase 1 assumption)
    depot_charger_slots: int = 0        # 0 = unlimited (Phase 2: shared charger scheduling)

    @property
    def route_codes(self) -> list[str]:
        return sorted(self.routes.keys())

    @property
    def total_configured_fleet(self) -> int:
        """Sum of fleet_size across all route configs."""
        return sum(ri.config.fleet_size for ri in self.routes.values())


@dataclass
class CitySchedule:
    """Complete citywide schedule output."""
    city_config: CityConfig
    results: dict[str, RouteResult]     # route_code → RouteResult
    transfers: list[Transfer] = field(default_factory=list)
    stability_flags: list = field(default_factory=list)  # list[StabilityFlag]
    # Phase 2: auto-generated recommendations
    recommendations: list = field(default_factory=list)  # list[Recommendation]
    # Phase 3: corridor analysis results
    corridors: list = field(default_factory=list)  # list[CorridorAnalysis]

    # ── Aggregate KPIs ────────────────────────────────────────────────────────

    @property
    def total_buses_used(self) -> int:
        return sum(r.fleet_allocated for r in self.results.values())

    @property
    def total_revenue_trips(self) -> int:
        return sum(r.metrics.revenue_trips_assigned for r in self.results.values())

    @property
    def total_revenue_km(self) -> float:
        return sum(r.metrics.revenue_km for r in self.results.values())

    @property
    def total_dead_km(self) -> float:
        return sum(r.metrics.dead_km for r in self.results.values())

    @property
    def total_dead_trips(self) -> int:
        return sum(r.metrics.dead_trips for r in self.results.values())

    @property
    def total_km(self) -> float:
        return sum(r.metrics.total_km for r in self.results.values())

    @property
    def citywide_dead_km_ratio(self) -> float:
        total = self.total_revenue_km + self.total_dead_km
        return self.total_dead_km / total if total > 0 else 0.0

    @property
    def citywide_utilization_pct(self) -> float:
        """Fleet utilization = buses with >0 revenue trips / total buses."""
        active = sum(1 for r in self.results.values()
                     for b in r.buses if any(t.trip_type == "Revenue" for t in b.trips))
        return (active / self.total_buses_used * 100) if self.total_buses_used > 0 else 0.0

    @property
    def min_soc_citywide(self) -> float:
        return min((r.metrics.min_soc_seen for r in self.results.values()), default=100.0)

    @property
    def avg_headway_deviation_min(self) -> float:
        """
        Mean absolute deviation between actual departure gaps and configured headway,
        across all routes and directions.

        For each consecutive revenue departure pair (same direction):
            deviation = |actual_gap_min - configured_headway_min_at(departure_time)|

        Returns the mean across all such pairs citywide, or 0.0 if no data.
        """
        from datetime import datetime as _dt
        deviations = []
        REF = _dt(2025, 1, 1)

        for r in self.results.values():
            # Build a simple headway lookup: sorted list of (start_min, hw_min)
            hw_bands = []
            try:
                for _, row in r.headway_df.iterrows():
                    t_from = row["time_from"]
                    hw     = float(row["headway_min"])
                    mins   = (t_from.hour * 60 + t_from.minute
                              if hasattr(t_from, "hour")
                              else int(str(t_from).split(":")[0]) * 60 + int(str(t_from).split(":")[1]))
                    hw_bands.append((mins, hw))
                hw_bands.sort()
            except Exception:
                hw_bands = [(0, 30.0)]

            def _lookup_hw(dep_min: float) -> float:
                hw = hw_bands[0][1]
                for start, h in hw_bands:
                    if dep_min >= start:
                        hw = h
                return hw

            for direction in ("UP", "DN"):
                deps = sorted([
                    t.actual_departure
                    for b in r.buses for t in b.trips
                    if t.trip_type == "Revenue"
                    and t.direction == direction
                    and t.actual_departure is not None
                ])
                for i in range(1, len(deps)):
                    gap     = (deps[i] - deps[i-1]).total_seconds() / 60.0
                    dep_min = deps[i].hour * 60 + deps[i].minute
                    target  = _lookup_hw(dep_min)
                    deviations.append(abs(gap - target))

        return round(sum(deviations) / len(deviations), 1) if deviations else 0.0

    @property
    def max_headway_gap_min(self) -> float:
        """
        Largest single departure gap observed across all routes and directions.
        Useful for spotting service holes that the average would hide.
        """
        max_gap = 0.0
        for r in self.results.values():
            for direction in ("UP", "DN"):
                deps = sorted([
                    t.actual_departure
                    for b in r.buses for t in b.trips
                    if t.trip_type == "Revenue"
                    and t.direction == direction
                    and t.actual_departure is not None
                ])
                for i in range(1, len(deps)):
                    gap = (deps[i] - deps[i-1]).total_seconds() / 60.0
                    if gap > max_gap:
                        max_gap = gap
        return round(max_gap, 1)

    def route_summary_rows(self) -> list[dict]:
        """One row per route for the dashboard summary table."""
        rows = []
        for code in sorted(self.results):
            r = self.results[code]
            m = r.metrics
            donated = sum(1 for t in self.transfers if t.from_route == code)
            received = sum(1 for t in self.transfers if t.to_route == code)
            rows.append({
                "Route": code,
                "Name": r.config.route_name,
                "Category": getattr(r.config, "route_category", "standard"),
                "PVR": r.pvr,
                "Config Fleet": r.fleet_original,
                "Allocated": r.fleet_allocated,
                "Donated": donated,
                "Received": received,
                "Rev Trips": m.revenue_trips_assigned,
                "Rev KM": round(m.revenue_km, 1),
                "Dead KM": round(m.dead_km, 1),
                "Dead %": f"{m.dead_km_ratio:.1%}",
                "Min SOC": f"{m.min_soc_seen:.1f}%",
                "LOS": getattr(m, "los_grade", ""),
                "Avg Wait": f"{getattr(m, 'avg_wait_min', 0):.0f} min",
                "Score": f"{m.weighted_score():.4f}",
            })
        return rows

    @property
    def planning_summary(self) -> dict:
        """
        Auto-generated planning summary — the first thing the planner sees.
        Returns a dict with sections: fleet, service_quality, warnings.
        """
        summary = {
            "fleet": {},
            "service_quality": {},
            "warnings": [],
        }

        # ── Fleet overview ────────────────────────────────────────────────
        total_fleet = self.total_buses_used
        total_pvr = sum(r.pvr for r in self.results.values())
        total_surplus = max(0, total_fleet - total_pvr)
        total_deficit = max(0, total_pvr - total_fleet)
        summary["fleet"] = {
            "total_allocated": total_fleet,
            "total_pvr": total_pvr,
            "surplus": total_surplus,
            "deficit": total_deficit,
            "routes_with_deficit": [
                code for code, r in self.results.items()
                if r.fleet_allocated < r.pvr
            ],
        }

        # ── Service quality ───────────────────────────────────────────────
        los_grades = {}
        routes_below_los_c = []
        for code, r in self.results.items():
            grade = getattr(r.metrics, "los_grade", "")
            los_grades[code] = grade
            if grade in ("D", "E", "F"):
                routes_below_los_c.append({
                    "route": code,
                    "los": grade,
                    "headway_cv": round(r.metrics.headway_cv, 3),
                    "max_gap_min": round(r.metrics.max_headway_gap_min, 0),
                    "avg_wait_min": round(getattr(r.metrics, "avg_wait_min", 0), 1),
                })

        # Citywide avg LOS (weighted by revenue trips)
        grade_to_num = {"A": 1, "B": 2, "C": 3, "D": 4, "E": 5, "F": 6}
        total_weight = sum(r.metrics.revenue_trips_assigned for r in self.results.values())
        if total_weight > 0:
            weighted_sum = sum(
                grade_to_num.get(getattr(r.metrics, "los_grade", "C"), 3) * r.metrics.revenue_trips_assigned
                for r in self.results.values()
            )
            avg_num = weighted_sum / total_weight
            num_to_grade = {v: k for k, v in grade_to_num.items()}
            citywide_los = num_to_grade.get(round(avg_num), "C")
        else:
            citywide_los = "—"

        summary["service_quality"] = {
            "citywide_los": citywide_los,
            "routes_below_los_c": routes_below_los_c,
            "total_revenue_trips": self.total_revenue_trips,
            "total_revenue_km": round(self.total_revenue_km, 1),
            "citywide_dead_km_ratio": f"{self.citywide_dead_km_ratio:.1%}",
            "min_soc_citywide": f"{self.min_soc_citywide:.1f}%",
        }

        # ── Warnings ──────────────────────────────────────────────────────
        # SOC risks
        for code, r in self.results.items():
            if r.metrics.min_soc_seen < r.config.min_soc_percent + 5:
                summary["warnings"].append(
                    f"⚠ SOC risk on {code}: min SOC = {r.metrics.min_soc_seen:.1f}% "
                    f"(floor = {r.config.min_soc_percent}%, margin only "
                    f"{r.metrics.min_soc_seen - r.config.min_soc_percent:.1f}%)"
                )

        # Headway infeasibilities
        for code, r in self.results.items():
            status = getattr(r, "headway_feasibility_status", "UNKNOWN")
            if status == "INFEASIBLE":
                details = getattr(r, "headway_feasibility_details", []) or []
                infeasible_bands = [
                    d for d in details
                    if isinstance(d, dict) and d.get("status") == "INFEASIBLE"
                ]
                if infeasible_bands:
                    band_str = ", ".join(
                        str(d.get("band", "?")) for d in infeasible_bands[:3]
                    )
                    summary["warnings"].append(
                        f"⚠ {code} headway infeasible in bands: {band_str}. "
                        f"Scheduler used physics minimum instead of configured value."
                    )

        # Fleet deficit
        if total_deficit > 0:
            deficit_routes = summary["fleet"]["routes_with_deficit"]
            summary["warnings"].append(
                f"⚠ Fleet deficit: {total_deficit} buses short citywide. "
                f"Affected routes: {', '.join(deficit_routes)}"
            )

        return summary
